"""update user table with last_played

Revision ID: 4617bc0b9adc
Revises: 39a3b85c935f
Create Date: 2026-05-27 19:42:28.114760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4617bc0b9adc'
down_revision: Union[str, Sequence[str], None] = '39a3b85c935f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_played', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_played')
    # ### end Alembic commands ###
