"""add rating and league fields

Revision ID: 8d3d3638275c
Revises: a8ee28ece428
Create Date: 2026-05-29 17:03:58.302998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3d3638275c'
down_revision: Union[str, Sequence[str], None] = 'a8ee28ece428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=False, server_default=sa.text('1000')))
    op.add_column('users', sa.Column('league', sa.String(), nullable=False, server_default=sa.text("'silver'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'league')
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
