"""init

Revision ID: e805a2b4fd8e
Revises: 
Create Date: 2026-05-13 21:49:34.292083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e805a2b4fd8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mascot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('opponent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('score_player', sa.Integer(), nullable=False),
    sa.Column('score_opponent', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_player_id'), 'battles', ['player_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('age_years', sa.Float(), nullable=False),
    sa.Column('contributors', sa.Integer(), nullable=False),
    sa.Column('activity_score', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('language_matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_lang_id', sa.Integer(), nullable=False),
    sa.Column('loser_lang_id', sa.Integer(), nullable=False),
    sa.Column('flavor_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['loser_lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['winner_lang_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('p1_card_id', sa.Integer(), nullable=False),
    sa.Column('p2_card_id', sa.Integer(), nullable=False),
    sa.Column('stat_chosen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('was_tie', sa.Boolean(), nullable=False),
    sa.Column('was_critical', sa.Boolean(), nullable=False),
    sa.Column('type_advantage', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['p1_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['p2_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_battle_id'), 'rounds', ['battle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_battle_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('language_matchups')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_battles_player_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
